// source: Messages.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest', null, global);
goog.exportSymbol('proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse', null, global);
goog.exportSymbol('proto.org.mosim.refactorlizar.messages.Error', null, global);
goog.exportSymbol('proto.org.mosim.refactorlizar.messages.Metric', null, global);
goog.exportSymbol('proto.org.mosim.refactorlizar.messages.Offset', null, global);
goog.exportSymbol('proto.org.mosim.refactorlizar.messages.Project', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.displayName = 'proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.displayName = 'proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.mosim.refactorlizar.messages.Error = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.mosim.refactorlizar.messages.Error, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.mosim.refactorlizar.messages.Error.displayName = 'proto.org.mosim.refactorlizar.messages.Error';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.mosim.refactorlizar.messages.Metric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.mosim.refactorlizar.messages.Metric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.mosim.refactorlizar.messages.Metric.displayName = 'proto.org.mosim.refactorlizar.messages.Metric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.mosim.refactorlizar.messages.Project = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.org.mosim.refactorlizar.messages.Project.repeatedFields_, null);
};
goog.inherits(proto.org.mosim.refactorlizar.messages.Project, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.mosim.refactorlizar.messages.Project.displayName = 'proto.org.mosim.refactorlizar.messages.Project';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: (f = msg.getProject()) && proto.org.mosim.refactorlizar.messages.Project.toObject(includeInstance, f),
    offset: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest;
  return proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.org.mosim.refactorlizar.messages.Project;
      reader.readMessage(value,proto.org.mosim.refactorlizar.messages.Project.deserializeBinaryFromReader);
      msg.setProject(value);
      break;
    case 2:
      var value = /** @type {!proto.org.mosim.refactorlizar.messages.Offset} */ (reader.readEnum());
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.org.mosim.refactorlizar.messages.Project.serializeBinaryToWriter
    );
  }
  f = message.getOffset();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional Project project = 1;
 * @return {?proto.org.mosim.refactorlizar.messages.Project}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.getProject = function() {
  return /** @type{?proto.org.mosim.refactorlizar.messages.Project} */ (
    jspb.Message.getWrapperField(this, proto.org.mosim.refactorlizar.messages.Project, 1));
};


/**
 * @param {?proto.org.mosim.refactorlizar.messages.Project|undefined} value
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} returns this
*/
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.setProject = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} returns this
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.clearProject = function() {
  return this.setProject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.hasProject = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Offset offset = 2;
 * @return {!proto.org.mosim.refactorlizar.messages.Offset}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.getOffset = function() {
  return /** @type {!proto.org.mosim.refactorlizar.messages.Offset} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.org.mosim.refactorlizar.messages.Offset} value
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest} returns this
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest.prototype.setOffset = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: (f = msg.getError()) && proto.org.mosim.refactorlizar.messages.Error.toObject(includeInstance, f),
    metrics: (f = msg.getMetrics()) && proto.org.mosim.refactorlizar.messages.Metric.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse;
  return proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.org.mosim.refactorlizar.messages.Error;
      reader.readMessage(value,proto.org.mosim.refactorlizar.messages.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 2:
      var value = new proto.org.mosim.refactorlizar.messages.Metric;
      reader.readMessage(value,proto.org.mosim.refactorlizar.messages.Metric.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.org.mosim.refactorlizar.messages.Error.serializeBinaryToWriter
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.org.mosim.refactorlizar.messages.Metric.serializeBinaryToWriter
    );
  }
};


/**
 * optional Error error = 1;
 * @return {?proto.org.mosim.refactorlizar.messages.Error}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.getError = function() {
  return /** @type{?proto.org.mosim.refactorlizar.messages.Error} */ (
    jspb.Message.getWrapperField(this, proto.org.mosim.refactorlizar.messages.Error, 1));
};


/**
 * @param {?proto.org.mosim.refactorlizar.messages.Error|undefined} value
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} returns this
*/
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} returns this
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Metric metrics = 2;
 * @return {?proto.org.mosim.refactorlizar.messages.Metric}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.getMetrics = function() {
  return /** @type{?proto.org.mosim.refactorlizar.messages.Metric} */ (
    jspb.Message.getWrapperField(this, proto.org.mosim.refactorlizar.messages.Metric, 2));
};


/**
 * @param {?proto.org.mosim.refactorlizar.messages.Metric|undefined} value
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} returns this
*/
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse} returns this
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.mosim.refactorlizar.messages.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.org.mosim.refactorlizar.messages.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.mosim.refactorlizar.messages.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.mosim.refactorlizar.messages.Error}
 */
proto.org.mosim.refactorlizar.messages.Error.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.mosim.refactorlizar.messages.Error;
  return proto.org.mosim.refactorlizar.messages.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.mosim.refactorlizar.messages.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.mosim.refactorlizar.messages.Error}
 */
proto.org.mosim.refactorlizar.messages.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.mosim.refactorlizar.messages.Error.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.mosim.refactorlizar.messages.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.mosim.refactorlizar.messages.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.org.mosim.refactorlizar.messages.Error.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.mosim.refactorlizar.messages.Error} returns this
 */
proto.org.mosim.refactorlizar.messages.Error.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.toObject = function(opt_includeInstance) {
  return proto.org.mosim.refactorlizar.messages.Metric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.mosim.refactorlizar.messages.Metric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Metric.toObject = function(includeInstance, msg) {
  var f, obj = {
    cohesion: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    complexity: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    coupling: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.mosim.refactorlizar.messages.Metric}
 */
proto.org.mosim.refactorlizar.messages.Metric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.mosim.refactorlizar.messages.Metric;
  return proto.org.mosim.refactorlizar.messages.Metric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.mosim.refactorlizar.messages.Metric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.mosim.refactorlizar.messages.Metric}
 */
proto.org.mosim.refactorlizar.messages.Metric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCohesion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setComplexity(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCoupling(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.mosim.refactorlizar.messages.Metric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.mosim.refactorlizar.messages.Metric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Metric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCohesion();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getComplexity();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getCoupling();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional double cohesion = 1;
 * @return {number}
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.getCohesion = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.mosim.refactorlizar.messages.Metric} returns this
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.setCohesion = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double complexity = 2;
 * @return {number}
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.getComplexity = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.mosim.refactorlizar.messages.Metric} returns this
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.setComplexity = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double coupling = 3;
 * @return {number}
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.getCoupling = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.mosim.refactorlizar.messages.Metric} returns this
 */
proto.org.mosim.refactorlizar.messages.Metric.prototype.setCoupling = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.org.mosim.refactorlizar.messages.Project.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.toObject = function(opt_includeInstance) {
  return proto.org.mosim.refactorlizar.messages.Project.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.mosim.refactorlizar.messages.Project} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Project.toObject = function(includeInstance, msg) {
  var f, obj = {
    languagePathsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    simulatorPathsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.mosim.refactorlizar.messages.Project}
 */
proto.org.mosim.refactorlizar.messages.Project.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.mosim.refactorlizar.messages.Project;
  return proto.org.mosim.refactorlizar.messages.Project.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.mosim.refactorlizar.messages.Project} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.mosim.refactorlizar.messages.Project}
 */
proto.org.mosim.refactorlizar.messages.Project.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addLanguagePaths(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addSimulatorPaths(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.mosim.refactorlizar.messages.Project.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.mosim.refactorlizar.messages.Project} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.mosim.refactorlizar.messages.Project.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLanguagePathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getSimulatorPathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * repeated string language_paths = 1;
 * @return {!Array<string>}
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.getLanguagePathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.setLanguagePathsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.addLanguagePaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.clearLanguagePathsList = function() {
  return this.setLanguagePathsList([]);
};


/**
 * repeated string simulator_paths = 2;
 * @return {!Array<string>}
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.getSimulatorPathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.setSimulatorPathsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.addSimulatorPaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.org.mosim.refactorlizar.messages.Project} returns this
 */
proto.org.mosim.refactorlizar.messages.Project.prototype.clearSimulatorPathsList = function() {
  return this.setSimulatorPathsList([]);
};


/**
 * @enum {number}
 */
proto.org.mosim.refactorlizar.messages.Offset = {
  NO_OFFSET: 0,
  ONE_OFFSET: 1
};

goog.object.extend(exports, proto.org.mosim.refactorlizar.messages);
