// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

/**
 * Protobuf type {@code org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse}
 */
public final class ArchitectureEvaluationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)
    ArchitectureEvaluationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArchitectureEvaluationResponse.newBuilder() to construct.
  private ArchitectureEvaluationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArchitectureEvaluationResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ArchitectureEvaluationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ArchitectureEvaluationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mosim.refactorlizar.messages.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(org.mosim.refactorlizar.messages.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mosim.refactorlizar.messages.Metric.Builder subBuilder = null;
            if (metrics_ != null) {
              subBuilder = metrics_.toBuilder();
            }
            metrics_ = input.readMessage(org.mosim.refactorlizar.messages.Metric.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metrics_);
              metrics_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_ArchitectureEvaluationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_ArchitectureEvaluationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.class, org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private org.mosim.refactorlizar.messages.Error error_;
  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   * @return The error.
   */
  @java.lang.Override
  public org.mosim.refactorlizar.messages.Error getError() {
    return error_ == null ? org.mosim.refactorlizar.messages.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   */
  @java.lang.Override
  public org.mosim.refactorlizar.messages.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  public static final int METRICS_FIELD_NUMBER = 2;
  private org.mosim.refactorlizar.messages.Metric metrics_;
  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   * @return Whether the metrics field is set.
   */
  @java.lang.Override
  public boolean hasMetrics() {
    return metrics_ != null;
  }
  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   * @return The metrics.
   */
  @java.lang.Override
  public org.mosim.refactorlizar.messages.Metric getMetrics() {
    return metrics_ == null ? org.mosim.refactorlizar.messages.Metric.getDefaultInstance() : metrics_;
  }
  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   */
  @java.lang.Override
  public org.mosim.refactorlizar.messages.MetricOrBuilder getMetricsOrBuilder() {
    return getMetrics();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    if (metrics_ != null) {
      output.writeMessage(2, getMetrics());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (metrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetrics());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)) {
      return super.equals(obj);
    }
    org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse other = (org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse) obj;

    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (hasMetrics() != other.hasMetrics()) return false;
    if (hasMetrics()) {
      if (!getMetrics()
          .equals(other.getMetrics())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasMetrics()) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetrics().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)
      org.mosim.refactorlizar.messages.ArchitectureEvaluationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_ArchitectureEvaluationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_ArchitectureEvaluationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.class, org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.Builder.class);
    }

    // Construct using org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      if (metricsBuilder_ == null) {
        metrics_ = null;
      } else {
        metrics_ = null;
        metricsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_ArchitectureEvaluationResponse_descriptor;
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse getDefaultInstanceForType() {
      return org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse build() {
      org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse buildPartial() {
      org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse result = new org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      if (metricsBuilder_ == null) {
        result.metrics_ = metrics_;
      } else {
        result.metrics_ = metricsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse) {
        return mergeFrom((org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse other) {
      if (other == org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.hasMetrics()) {
        mergeMetrics(other.getMetrics());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.mosim.refactorlizar.messages.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mosim.refactorlizar.messages.Error, org.mosim.refactorlizar.messages.Error.Builder, org.mosim.refactorlizar.messages.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     * @return The error.
     */
    public org.mosim.refactorlizar.messages.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? org.mosim.refactorlizar.messages.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public Builder setError(org.mosim.refactorlizar.messages.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public Builder setError(
        org.mosim.refactorlizar.messages.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public Builder mergeError(org.mosim.refactorlizar.messages.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            org.mosim.refactorlizar.messages.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public org.mosim.refactorlizar.messages.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    public org.mosim.refactorlizar.messages.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            org.mosim.refactorlizar.messages.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mosim.refactorlizar.messages.Error, org.mosim.refactorlizar.messages.Error.Builder, org.mosim.refactorlizar.messages.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mosim.refactorlizar.messages.Error, org.mosim.refactorlizar.messages.Error.Builder, org.mosim.refactorlizar.messages.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private org.mosim.refactorlizar.messages.Metric metrics_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mosim.refactorlizar.messages.Metric, org.mosim.refactorlizar.messages.Metric.Builder, org.mosim.refactorlizar.messages.MetricOrBuilder> metricsBuilder_;
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     * @return Whether the metrics field is set.
     */
    public boolean hasMetrics() {
      return metricsBuilder_ != null || metrics_ != null;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     * @return The metrics.
     */
    public org.mosim.refactorlizar.messages.Metric getMetrics() {
      if (metricsBuilder_ == null) {
        return metrics_ == null ? org.mosim.refactorlizar.messages.Metric.getDefaultInstance() : metrics_;
      } else {
        return metricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public Builder setMetrics(org.mosim.refactorlizar.messages.Metric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metrics_ = value;
        onChanged();
      } else {
        metricsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public Builder setMetrics(
        org.mosim.refactorlizar.messages.Metric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        metrics_ = builderForValue.build();
        onChanged();
      } else {
        metricsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public Builder mergeMetrics(org.mosim.refactorlizar.messages.Metric value) {
      if (metricsBuilder_ == null) {
        if (metrics_ != null) {
          metrics_ =
            org.mosim.refactorlizar.messages.Metric.newBuilder(metrics_).mergeFrom(value).buildPartial();
        } else {
          metrics_ = value;
        }
        onChanged();
      } else {
        metricsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public Builder clearMetrics() {
      if (metricsBuilder_ == null) {
        metrics_ = null;
        onChanged();
      } else {
        metrics_ = null;
        metricsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public org.mosim.refactorlizar.messages.Metric.Builder getMetricsBuilder() {
      
      onChanged();
      return getMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    public org.mosim.refactorlizar.messages.MetricOrBuilder getMetricsOrBuilder() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilder();
      } else {
        return metrics_ == null ?
            org.mosim.refactorlizar.messages.Metric.getDefaultInstance() : metrics_;
      }
    }
    /**
     * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mosim.refactorlizar.messages.Metric, org.mosim.refactorlizar.messages.Metric.Builder, org.mosim.refactorlizar.messages.MetricOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mosim.refactorlizar.messages.Metric, org.mosim.refactorlizar.messages.Metric.Builder, org.mosim.refactorlizar.messages.MetricOrBuilder>(
                getMetrics(),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)
  }

  // @@protoc_insertion_point(class_scope:org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)
  private static final org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse();
  }

  public static org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArchitectureEvaluationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ArchitectureEvaluationResponse>() {
    @java.lang.Override
    public ArchitectureEvaluationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ArchitectureEvaluationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ArchitectureEvaluationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArchitectureEvaluationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

