// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

public interface ArchitectureEvaluationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.mosim.refactorlizar.messages.ArchitectureEvaluationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.mosim.refactorlizar.messages.Project project = 1;</code>
   * @return Whether the project field is set.
   */
  boolean hasProject();
  /**
   * <code>.org.mosim.refactorlizar.messages.Project project = 1;</code>
   * @return The project.
   */
  org.mosim.refactorlizar.messages.Project getProject();
  /**
   * <code>.org.mosim.refactorlizar.messages.Project project = 1;</code>
   */
  org.mosim.refactorlizar.messages.ProjectOrBuilder getProjectOrBuilder();

  /**
   * <code>.org.mosim.refactorlizar.messages.Offset offset = 2;</code>
   * @return The enum numeric value on the wire for offset.
   */
  int getOffsetValue();
  /**
   * <code>.org.mosim.refactorlizar.messages.Offset offset = 2;</code>
   * @return The offset.
   */
  org.mosim.refactorlizar.messages.Offset getOffset();
}
