// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

public interface ArchitectureEvaluationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.mosim.refactorlizar.messages.ArchitectureEvaluationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   * @return The error.
   */
  org.mosim.refactorlizar.messages.Error getError();
  /**
   * <code>.org.mosim.refactorlizar.messages.Error error = 1;</code>
   */
  org.mosim.refactorlizar.messages.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   * @return Whether the metrics field is set.
   */
  boolean hasMetrics();
  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   * @return The metrics.
   */
  org.mosim.refactorlizar.messages.Metric getMetrics();
  /**
   * <code>.org.mosim.refactorlizar.messages.Metric metrics = 2;</code>
   */
  org.mosim.refactorlizar.messages.MetricOrBuilder getMetricsOrBuilder();
}
