// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.mosim.refactorlizar.messages.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
