// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

public interface MetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.mosim.refactorlizar.messages.Metric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double cohesion = 1;</code>
   * @return The cohesion.
   */
  double getCohesion();

  /**
   * <code>double complexity = 2;</code>
   * @return The complexity.
   */
  double getComplexity();

  /**
   * <code>double coupling = 3;</code>
   * @return The coupling.
   */
  double getCoupling();
}
