// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

/**
 * Protobuf enum {@code org.mosim.refactorlizar.messages.Offset}
 */
public enum Offset
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NO_OFFSET = 0;</code>
   */
  NO_OFFSET(0),
  /**
   * <code>ONE_OFFSET = 1;</code>
   */
  ONE_OFFSET(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NO_OFFSET = 0;</code>
   */
  public static final int NO_OFFSET_VALUE = 0;
  /**
   * <code>ONE_OFFSET = 1;</code>
   */
  public static final int ONE_OFFSET_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Offset valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Offset forNumber(int value) {
    switch (value) {
      case 0: return NO_OFFSET;
      case 1: return ONE_OFFSET;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Offset>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Offset> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Offset>() {
          public Offset findValueByNumber(int number) {
            return Offset.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.mosim.refactorlizar.messages.Messages.getDescriptor().getEnumTypes().get(0);
  }

  private static final Offset[] VALUES = values();

  public static Offset valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Offset(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.mosim.refactorlizar.messages.Offset)
}

