// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.mosim.refactorlizar.messages;

/**
 * Protobuf type {@code org.mosim.refactorlizar.messages.Project}
 */
public final class Project extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.mosim.refactorlizar.messages.Project)
    ProjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Project.newBuilder() to construct.
  private Project(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Project() {
    languagePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    simulatorPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Project();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Project(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              languagePaths_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            languagePaths_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              simulatorPaths_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            simulatorPaths_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        languagePaths_ = languagePaths_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        simulatorPaths_ = simulatorPaths_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_Project_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_Project_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mosim.refactorlizar.messages.Project.class, org.mosim.refactorlizar.messages.Project.Builder.class);
  }

  public static final int LANGUAGE_PATHS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList languagePaths_;
  /**
   * <code>repeated string language_paths = 1;</code>
   * @return A list containing the languagePaths.
   */
  public com.google.protobuf.ProtocolStringList
      getLanguagePathsList() {
    return languagePaths_;
  }
  /**
   * <code>repeated string language_paths = 1;</code>
   * @return The count of languagePaths.
   */
  public int getLanguagePathsCount() {
    return languagePaths_.size();
  }
  /**
   * <code>repeated string language_paths = 1;</code>
   * @param index The index of the element to return.
   * @return The languagePaths at the given index.
   */
  public java.lang.String getLanguagePaths(int index) {
    return languagePaths_.get(index);
  }
  /**
   * <code>repeated string language_paths = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the languagePaths at the given index.
   */
  public com.google.protobuf.ByteString
      getLanguagePathsBytes(int index) {
    return languagePaths_.getByteString(index);
  }

  public static final int SIMULATOR_PATHS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList simulatorPaths_;
  /**
   * <code>repeated string simulator_paths = 2;</code>
   * @return A list containing the simulatorPaths.
   */
  public com.google.protobuf.ProtocolStringList
      getSimulatorPathsList() {
    return simulatorPaths_;
  }
  /**
   * <code>repeated string simulator_paths = 2;</code>
   * @return The count of simulatorPaths.
   */
  public int getSimulatorPathsCount() {
    return simulatorPaths_.size();
  }
  /**
   * <code>repeated string simulator_paths = 2;</code>
   * @param index The index of the element to return.
   * @return The simulatorPaths at the given index.
   */
  public java.lang.String getSimulatorPaths(int index) {
    return simulatorPaths_.get(index);
  }
  /**
   * <code>repeated string simulator_paths = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the simulatorPaths at the given index.
   */
  public com.google.protobuf.ByteString
      getSimulatorPathsBytes(int index) {
    return simulatorPaths_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < languagePaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, languagePaths_.getRaw(i));
    }
    for (int i = 0; i < simulatorPaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, simulatorPaths_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < languagePaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(languagePaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLanguagePathsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < simulatorPaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(simulatorPaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSimulatorPathsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mosim.refactorlizar.messages.Project)) {
      return super.equals(obj);
    }
    org.mosim.refactorlizar.messages.Project other = (org.mosim.refactorlizar.messages.Project) obj;

    if (!getLanguagePathsList()
        .equals(other.getLanguagePathsList())) return false;
    if (!getSimulatorPathsList()
        .equals(other.getSimulatorPathsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLanguagePathsCount() > 0) {
      hash = (37 * hash) + LANGUAGE_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getLanguagePathsList().hashCode();
    }
    if (getSimulatorPathsCount() > 0) {
      hash = (37 * hash) + SIMULATOR_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getSimulatorPathsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mosim.refactorlizar.messages.Project parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.Project parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.Project parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mosim.refactorlizar.messages.Project parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mosim.refactorlizar.messages.Project prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.mosim.refactorlizar.messages.Project}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.mosim.refactorlizar.messages.Project)
      org.mosim.refactorlizar.messages.ProjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_Project_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_Project_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mosim.refactorlizar.messages.Project.class, org.mosim.refactorlizar.messages.Project.Builder.class);
    }

    // Construct using org.mosim.refactorlizar.messages.Project.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      languagePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      simulatorPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mosim.refactorlizar.messages.Messages.internal_static_org_mosim_refactorlizar_messages_Project_descriptor;
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.Project getDefaultInstanceForType() {
      return org.mosim.refactorlizar.messages.Project.getDefaultInstance();
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.Project build() {
      org.mosim.refactorlizar.messages.Project result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mosim.refactorlizar.messages.Project buildPartial() {
      org.mosim.refactorlizar.messages.Project result = new org.mosim.refactorlizar.messages.Project(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        languagePaths_ = languagePaths_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.languagePaths_ = languagePaths_;
      if (((bitField0_ & 0x00000002) != 0)) {
        simulatorPaths_ = simulatorPaths_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.simulatorPaths_ = simulatorPaths_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mosim.refactorlizar.messages.Project) {
        return mergeFrom((org.mosim.refactorlizar.messages.Project)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mosim.refactorlizar.messages.Project other) {
      if (other == org.mosim.refactorlizar.messages.Project.getDefaultInstance()) return this;
      if (!other.languagePaths_.isEmpty()) {
        if (languagePaths_.isEmpty()) {
          languagePaths_ = other.languagePaths_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLanguagePathsIsMutable();
          languagePaths_.addAll(other.languagePaths_);
        }
        onChanged();
      }
      if (!other.simulatorPaths_.isEmpty()) {
        if (simulatorPaths_.isEmpty()) {
          simulatorPaths_ = other.simulatorPaths_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureSimulatorPathsIsMutable();
          simulatorPaths_.addAll(other.simulatorPaths_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mosim.refactorlizar.messages.Project parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mosim.refactorlizar.messages.Project) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList languagePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLanguagePathsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        languagePaths_ = new com.google.protobuf.LazyStringArrayList(languagePaths_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @return A list containing the languagePaths.
     */
    public com.google.protobuf.ProtocolStringList
        getLanguagePathsList() {
      return languagePaths_.getUnmodifiableView();
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @return The count of languagePaths.
     */
    public int getLanguagePathsCount() {
      return languagePaths_.size();
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param index The index of the element to return.
     * @return The languagePaths at the given index.
     */
    public java.lang.String getLanguagePaths(int index) {
      return languagePaths_.get(index);
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the languagePaths at the given index.
     */
    public com.google.protobuf.ByteString
        getLanguagePathsBytes(int index) {
      return languagePaths_.getByteString(index);
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param index The index to set the value at.
     * @param value The languagePaths to set.
     * @return This builder for chaining.
     */
    public Builder setLanguagePaths(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLanguagePathsIsMutable();
      languagePaths_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param value The languagePaths to add.
     * @return This builder for chaining.
     */
    public Builder addLanguagePaths(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLanguagePathsIsMutable();
      languagePaths_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param values The languagePaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllLanguagePaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureLanguagePathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, languagePaths_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguagePaths() {
      languagePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string language_paths = 1;</code>
     * @param value The bytes of the languagePaths to add.
     * @return This builder for chaining.
     */
    public Builder addLanguagePathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLanguagePathsIsMutable();
      languagePaths_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList simulatorPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSimulatorPathsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        simulatorPaths_ = new com.google.protobuf.LazyStringArrayList(simulatorPaths_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @return A list containing the simulatorPaths.
     */
    public com.google.protobuf.ProtocolStringList
        getSimulatorPathsList() {
      return simulatorPaths_.getUnmodifiableView();
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @return The count of simulatorPaths.
     */
    public int getSimulatorPathsCount() {
      return simulatorPaths_.size();
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param index The index of the element to return.
     * @return The simulatorPaths at the given index.
     */
    public java.lang.String getSimulatorPaths(int index) {
      return simulatorPaths_.get(index);
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the simulatorPaths at the given index.
     */
    public com.google.protobuf.ByteString
        getSimulatorPathsBytes(int index) {
      return simulatorPaths_.getByteString(index);
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param index The index to set the value at.
     * @param value The simulatorPaths to set.
     * @return This builder for chaining.
     */
    public Builder setSimulatorPaths(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSimulatorPathsIsMutable();
      simulatorPaths_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param value The simulatorPaths to add.
     * @return This builder for chaining.
     */
    public Builder addSimulatorPaths(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSimulatorPathsIsMutable();
      simulatorPaths_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param values The simulatorPaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllSimulatorPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureSimulatorPathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, simulatorPaths_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSimulatorPaths() {
      simulatorPaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string simulator_paths = 2;</code>
     * @param value The bytes of the simulatorPaths to add.
     * @return This builder for chaining.
     */
    public Builder addSimulatorPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSimulatorPathsIsMutable();
      simulatorPaths_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.mosim.refactorlizar.messages.Project)
  }

  // @@protoc_insertion_point(class_scope:org.mosim.refactorlizar.messages.Project)
  private static final org.mosim.refactorlizar.messages.Project DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mosim.refactorlizar.messages.Project();
  }

  public static org.mosim.refactorlizar.messages.Project getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Project>
      PARSER = new com.google.protobuf.AbstractParser<Project>() {
    @java.lang.Override
    public Project parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Project(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Project> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Project> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mosim.refactorlizar.messages.Project getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

